//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hadafDBEntities : DbContext
    {
        public hadafDBEntities()
            : base("name=hadafDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COMNP> COMNP { get; set; }
        public DbSet<COMP> COMP { get; set; }
        public DbSet<Counter> Counter { get; set; }
        public DbSet<enter> enter { get; set; }
        public DbSet<IT> IT { get; set; }
        public DbSet<KarB> KarB { get; set; }
        public DbSet<kardaninarm> kardaninarm { get; set; }
        public DbSet<KarG> KarG { get; set; }
        public DbSet<KarNC> KarNC { get; set; }
        public DbSet<KarNE> KarNE { get; set; }
        public DbSet<KarT> KarT { get; set; }
        public DbSet<KNC> KNC { get; set; }
        public DbSet<KNE> KNE { get; set; }
        public DbSet<KNG> KNG { get; set; }
        public DbSet<KNT> KNT { get; set; }
        public DbSet<KPE> KPE { get; set; }
        public DbSet<KPG> KPG { get; set; }
    }
}
