//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hadafDBEntities : DbContext
    {
        public hadafDBEntities()
            : base("name=hadafDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COMNP> COMNPs { get; set; }
        public DbSet<COMP> COMPs { get; set; }
        public DbSet<Counter> Counters { get; set; }
        public DbSet<enter> enters { get; set; }
        public DbSet<KarB> KarBs { get; set; }
        public DbSet<kardaninarm> kardaninarms { get; set; }
        public DbSet<KarG> KarGs { get; set; }
        public DbSet<KarM> KarMs { get; set; }
        public DbSet<KarNC> KarNCs { get; set; }
        public DbSet<KarNE> KarNEs { get; set; }
        public DbSet<KarT> KarTs { get; set; }
        public DbSet<KNC> KNCs { get; set; }
        public DbSet<KNE> KNEs { get; set; }
        public DbSet<KNG> KNGs { get; set; }
        public DbSet<KNT> KNTs { get; set; }
        public DbSet<KPE> KPEs { get; set; }
        public DbSet<KPG> KPGs { get; set; }
        public DbSet<ksanaye> ksanayes { get; set; }
        public DbSet<ReshteInT> ReshteInTs { get; set; }
        public DbSet<Student> Students { get; set; }
    }
}
